name: Docker Image CI

on:
  push:
    branches: main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - name: enable buildkit
      run: DOCKER_BUILDKIT=1
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push beer-service
      working-directory: merger/
      run: docker build --progress=plain . --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/merger:latest
