name: Docker Image CI

on:
  push:
    branches: main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18
    - 
      name: Build project with Maven
      run: mvn -T 1C package -DskipTests --file merger/pom.xml
    -  
      name: Build merger
      working-directory: merger/
      run: docker build --progress=plain . --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/merger:latest
    -
      name: Push merger
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/merger:latest
